### ISSUE TITLE
SVG Borders - Stage 5

### ISSUE THREAD

**Issue by aninde** [handsontable/quality#12]
## Fourth stage - acceptance, retests and regression test 
:information_source:  not checked - means _TODO_
- [ ] After fixing bugs found on the third stage https://github.com/handsontable/quality/issues/8

- [ ] Test PR that fixes https://github.com/handsontable/handsontable/issues/6646 and https://github.com/handsontable/handsontable/issues/6651
   - [ ] Conformance to requirements
   - [ ] Regression test

- [ ] Test Pr that adds new feature [Selection border style configuration through the settings object #6656](https://github.com/handsontable/handsontable/issues/6656)
  - [ ] Conformance to requirements
  - [ ] Regression test

### Tests to conduct

- [ ] `rem`, `em`, `Bootstrap`
- [ ] How does it look like on Firefox, Safari, Chrome, Edge and IE
- [ ] How does it look like on mobiles and Ipad
