### ISSUE TITLE
[HyperFormula]  Conformance: engine & comparison operators

### ISSUE THREAD

**Issue by aninde** [handsontable/quality#14]
### Description
We need to check conformance of comparison operators

- [x] <
- [x] >
- [x] <=
- [x] >=
- [x] =
- [x]  <>
- [x] all error types
- [ ] ?
- [x] : (range)
- [ ] ~
- [x] &
- [x] Comparrision to Excel 
['"A"', '"B"', '=A1>B1']`
Text A, Text B, Formuła
- [x] with enabled CASE_SENSITIVE
- [x] with disabled CASE_SENSITIVE
- [x] Does all operators are supported
- [ ]  Can parameters be a reference to another cell
- [ ] Are the correct errors returned when something went wrong
- [ ] How does it behave when parameters are out of bounds (eg. -1 when it should be >0)  

#### Types
- [x] type comparison
  - [x] same types
  - [x] different types
- [x] errors handle

#### Objects
 - [x] null

#### Numbers 
- [x] null
- [ ] NaN,
- [x] Infinity,
- [x] - Infinity,
- [x] -0, which the engine should not support. He shouldn't have crashed either
- [ ] how zero suppression is handled In JS we can write a number as .3, but in hyperformula it is a string, not always number
- [ ] precision 
- [x] very big numbers
- [x] very small numbers
- [x] the maximum and minimum number served. If the type is number then there will be a JS limit, but there is no such limit in the string.

## Stage 1 
- [x]  all Errors handling
- [ ] data types
- [ ]  type conversion

## Stage 2
New issue.

### Documentation
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare
https://github.com/handsontable/quality/issues/1#issuecomment-579207255

Parsing text to value:
https://gitlab.gnome.org/GNOME/gnumeric/blob/master/samples/excel/complex-parsing.xls

All operators and types combinations:
https://gitlab.gnome.org/GNOME/gnumeric/blob/master/samples/excel/operator.xls
GS v. https://docs.google.com/spreadsheets/d/1uwMSAOssKTo_rpbFDObPgux7BW3pIL3IiZp-FiJd1Xk/edit#gid=0

### Requirements
https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1017966_715980110
