### ISSUE TITLE
SVG Borders - Retesting issues

### ISSUE THREAD

**Issue by aninde** [handsontable/quality#15]
After merge with 8.0.0

#### Retests from stage 1 https://github.com/handsontable/handsontable/issues/6467#issuecomment-561557696
- [ ]  #4142 Custom border on fixed row 
- [ ] #4940 The selection doesn't work with merged cells with fixed overlays 
- [ ] #5298 Printing custom borders with bootstrap css 
- [ ] #5568 CustomBorders draws borders of width 2px+ incorrectly 
- [ ] #4993 The fragmentSelection doesn't draw all the borders in some cases
