### ISSUE TITLE
SVG - Stage 4

### ISSUE THREAD

**Issue by aninde** [handsontable/quality#16]
### Description
After fixing issues found in stage 3 #8 

### Testing checklist
- [ ] build Handsontable
- [ ] execute e2e tests in various browsers
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] Microsoft Dev Edge
  - [ ] Opera
- [ ] execute test for mobile devices
- [ ] mobile - manual tests

### Related issues - bugs found during stage 3 #8 
- [ ] https://github.com/handsontable/handsontable/issues/6665 loss of area.highlight border during scrolling
- [ ] https://github.com/handsontable/handsontable/issues/6666 Support for Bootstrap 
- [ ] https://github.com/handsontable/handsontable/issues/6667 blur while using `rem`, `em`, `Bootstrap` 
- [ ] https://github.com/handsontable/handsontable/issues/6671 selection flickers when autofill is on last column 

### Requirements
- [ ] Conformance to requirements of [svg-borders_PR](https://github.com/handsontable/handsontable/pull/6157) 
- [ ] Testing checklist https://github.com/handsontable/handsontable/issues/6467
