### ISSUE TITLE
[Tools] Make more advanced apps for test

### ISSUE THREAD

**Issue by aninde** [handsontable/quality#18]
### Description 

Preparation of more advanced but at the same time universal test environments to test Handsontable in conditions as close as possible to those used by our clients.

### Stage 1
- [x] design based on use cases
- [x] analysis with  marketing department
- [ ] analysis with support department

### Stage 2
- [ ] implementation
