### ISSUE TITLE
[HyperFormula] Kitchensink testing 

### ISSUE THREAD

**Issue by aninde** [handsontable/quality#2]
When https://github.com/handsontable/hyperformula/issues/17 will be ready.

### Testing checklist:

- [x] Compliance with requirements 
- [ ] Manual tests comparing working to Excel, Google Spreadsheet and Libra Ofice 
- [ ] Testing current API & hooks
    - [x] [`setDataAtCell`](https://handsontable.com/docs/7.3.0/Core.html#setDataAtCell)
    - [x] [`loadData`](https://handsontable.com/docs/7.3.0/Core.html#loadData)
    - [x] [`populateFromArray`](https://handsontable.com/docs/7.3.0/Core.html#populateFromArray)
    - [x] [`setDataAtRowProp`](https://handsontable.com/docs/7.3.0/Core.html#setDataAtRowProp)
    - [ ] [`updateSettings> data`](https://handsontable.com/docs/7.3.0/Core.html#updateSettings)
    - [ ] [`setCellMeta`](https://handsontable.com/docs/7.3.0/Core.html#setCellMeta)
    - [ ]  [`alter`](https://handsontable.com/docs/7.3.0/Core.html#alter) 
    - [ ] [`setCellMetaObject`](https://handsontable.com/docs/7.3.0/Core.html#setCellMetaObject)
    - [ ] [`getCopyableData`](https://handsontable.com/docs/7.3.0/Core.html#getCopyableData)
    - [ ] [`getCopyableText`](https://handsontable.com/docs/7.3.0/Core.html#getCopyableText)
    - [ ] [`setCommentAtCell`](https://handsontable.com/docs/7.3.0/Comments.html#setCommentAtCell)
    - [ ] [`setComment`](https://handsontable.com/docs/7.3.0/Comments.html#setComment)
   - [ ] [`removeCommentAtCell`](https://handsontable.com/docs/7.3.0/Comments.html#removeCommentAtCell)
  - [ ] [`removeComment`](https://handsontable.com/docs/7.3.0/Comments.html#removeComment)
- [ ] Integration with Handsontable 
- [ ] Formula plugin
    - [x] Any numbers, 
    - [x] negative and 
    - [x] positive 
    - [x] as float 
    - [x] or integer;
    - [x] Arithmetic operations such as: 
    - [x] +, 
    - [x] -,
    - [x]  /,
    - [x] *,
    - [x] %, 
    - [x] ^;
     - [ ] Logical operations such as: AND(), 
     - [ ]  OR(), 
     - [ ] NOT(), 
     - [ ] XOR();
     - [ ] Comparison operations such as: =, >, >=, <, <=, <>;
     - [ ] All JavaScript Math constants such as: PI(), E(), LN10(), LN2(), LOG10E(), LOG2E(), SQRT1_2(), SQRT2();
     - [ ] Error handling: #DIV/0!, #ERROR!, #VALUE!, #REF!, #NAME?, #N/A, #NUM!;
     - [x] String operations such as: & (concatenation eq. =-(2&5) will return -25);
     - [x] All excel formulas defined in formula.js;
     - [x] Relative and absolute cell references such as: A1, $A1, A$1, $A$1;
     - [x] Build-in variables such as: TRUE, FALSE, NULL;
     - [ ] Custom variables;
     - [ ] Nested functions;
     - [ ] Dynamic updates.
- [ ] Working of Handsontable should be compliance with [requirements](https://github.com/handsontable/handsontable/issues/6466)
- [ ] CRUD operations
- [x] Sorting
- [x] Filtering
- [x] contextMenu
- [ ] Formulas
- [ ] Formulas update
- [ ] Value calculation 
- [x] Integration of formulas in many Handsontable
- [x] Editors with a value other than text

### Related issues:
https://github.com/handsontable/handsontable/labels/Formulas
- [ ] [#3908](https://github.com/handsontable/handsontable/issues/3908)  perhaps an issue on formula 
- [ ] [#3975](https://github.com/handsontable/handsontable/issues/3975) Dropdown and Autocomplete should work without loading extra plugins
- [ ] [#4066](https://github.com/handsontable/handsontable/issues/4066) Formula does not get initially evaluated with column mapping 
- [ ] [#4154](https://github.com/handsontable/handsontable/issues/4154) formulas not init with nestedRows
- [ ] [#4353](https://github.com/handsontable/handsontable/issues/4353) When the cell type is numeric, the formula does not work properly.
- [ ] [#4357](https://github.com/handsontable/handsontable/issues/4357) https://github.com/handsontable/handsontable/issues/4357
- [ ] [#4430](https://github.com/handsontable/handsontable/issues/4430) Formulas does not apply for some cells
- [ ] [#4654](https://github.com/handsontable/handsontable/issues/4654) After inserting a row, an auto-updated formula displays incorrect value 
- [ ] [#4668](https://github.com/handsontable/handsontable/issues/4668) 
Formulas do not recalculate when we move columns
- [ ] [#4675](https://github.com/handsontable/handsontable/issues/4675) AVERAGE formula updates incorrectly
- [ ] [#4678](https://github.com/handsontable/handsontable/issues/4678) Formulas recalculates when we block a change via beforeChange
- [ ] [#4693](https://github.com/handsontable/handsontable/issues/4693) Handsontable should work without formula parser enabled
- [ ] [#5279](https://github.com/handsontable/handsontable/issues/5279) Bug in formula parsing when using nested data structures. 
- [ ] [#5455](https://github.com/handsontable/handsontable/issues/5455) Column with formulas doesn't filter properly
- [ ] [#5550](https://github.com/handsontable/handsontable/issues/5550) after remove columns get wrong sourceData with formulas enabled 
- [ ] [#5613](https://github.com/handsontable/handsontable/issues/5613) continus removeRow cause error in formula situation
- [ ] [#5635](https://github.com/handsontable/handsontable/issues/5635) Formulas don't update after row is removed
- [ ] [#5689](https://github.com/handsontable/handsontable/issues/5689) beforeChange event i cahnge a value, but the relate formula calculate wrong
- [ ] [#5852](https://github.com/handsontable/handsontable/issues/5852) Add case sensitive options for filters formulas
- [ ] [#5870](https://github.com/handsontable/handsontable/issues/5870) Calculation issue when IF is used on FALSE data
- [ ] [#5872](https://github.com/handsontable/handsontable/issues/5872) AVERAGE doesn't allow to define numbers as strings
- [ ] [#6248](https://github.com/handsontable/handsontable/issues/6248) Using clear() method breaks down formulas
- [ ] [#6336](https://github.com/handsontable/handsontable/issues/6336) Formulas are incorrectly calculated / auto updated on sort 
- [ ] [#/6359](https://github.com/handsontable/handsontable/issues/6359) Formula is converted to a value if merged areas are included 
- [ ] [#6480](https://github.com/handsontable/handsontable/issues/6480) It seems that the Formulas plugin doesn't work well with sorting

### Requirements
https://github.com/handsontable/handsontable/issues/6466
