### ISSUE TITLE
Testing release 7.4.0

### ISSUE THREAD

**Issue by aninde** [handsontable/quality#22]
### Description
Needs very in-depth testing.

Branch https://github.com/handsontable/handsontable/tree/release/7.4.0
RN
Updated draft https://github.com/handsontable/handsontable/releases/tag/untagged-293540147031a514c8ad
https://gist.github.com/jansiegel/ee77384ed74105522de199804f28fe13

#### Min  - for tests
https://gist.githack.com/aninde/42765ccf061dc35d64872d773e665a33/raw/db44b1c05c1f4f86dd598971a0dfc59289568874/handsontable.full.min.css

https://gist.githack.com/aninde/ca852b80f877ee757beffa91778fc0ed/raw/40f2da19718b870dda92e1d1226f2a120828756c/handsontable.full.min.js

#### Full
https://cdn.jsdelivr.net/gh/handsontable/handsontable@0e1af9c709a4b192019e6789d26dbc50dbda2fa4/dist/handsontable.full.css

https://cdn.jsdelivr.net/gh/handsontable/handsontable@0e1af9c709a4b192019e6789d26dbc50dbda2fa4/dist/handsontable.full.js 

### Testing checklist
- [x]  Build a version
- [x] Check the size of the version
- [x] Build a version and install with wrappers, check their size
- [x] Browser e2e tests on Chrome, Firefox, Safari, Opera, Edge
    `$ npm run test: e2e.dump`
    file is on `test/E2ERunner.html`  
- [x] Tests walkontable on Chrome, Firefox, Safari, Opera, Edge
      `$ test: walkontable.dump`
    file is on `src/3rdparty/walkontable/test/SpecRunner.html`
- [x] mobile - manual tests
- [x] test all CodeSandbox demos
- [x] check all related issues
- [x] columnSummary
- [x] Check the numeric type editor
     - [x] non-integer numbers, currency, commas, number format, formulas
     - [x] repeat above after changing the keyboard language to American
     - [x] and after changing the keyboard language to German
     - [x] IME after changing the language to Chinese or Japanese
- [x] Click through key functions on a minified version (crud, move, formulas)
- [x] Click through key functions (crud, move, fixing, formulas) on wrappers
- [ ] ~Validation check:~ cannot be done before release
    - [ ] ~Has the number of licenses changed?~ cannot be done
    - [ ] ~check key with incorrect date - when the license expires yesterday, today and tomorrow~
- [x] codesandbox Bot - add demo, check if bot builds new one
- [x] click throught contextMenu and dropdownMenu

 

### Related issues
- [x] **BLOCKER**[#6507](https://github.com/handsontable/handsontable/issues/6507) Fixed the problem, where the onCellMouseUp hook was fired for all mouse buttons except RMB, which was not consistent with the onCellMouseDown hook.
To make the changes more consistent with the native dblclick event (which is triggered only for the LMB button), the onCellDblClick and onCellCornerDblClick hooks were modified to also fire only for LMB. 
- [x] [#6610](https://github.com/handsontable/handsontable/pull/6610) Updated moment, pikaday and numbro to their latest versions.

##### Maybe they were corrected by the way by handsontable/handsontable#6610 (not inside Release Notes):
----
  - [x] 1. [#5159 Support newer versions of momentjs etc](https://github.com/handsontable/handsontable/issues/5159)
  - [x] 2. [#6110 License suggestion for R community: rhandsontable ](https://github.com/handsontable/handsontable/issues/6110)
  - [x] 3. [#5790 RangeError: toFixed() digits arguments must be between 0 and 100 ](https://github.com/handsontable/handsontable/issues/5790#issuecomment-471581724)
  - [x] 4. [#6582 We're not able to undo changes while using summary calculations and `numeric` cell data.](https://github.com/handsontable/handsontable/issues/6582)
  - [x] 5. ~[#6423 The column type: data is not protected against pasting data using autoFill / fillHandle ](https://github.com/handsontable/handsontable/issues/6423)~
not in scope
  - [x] 6. [#5863 We get `Maximum call stack size exceeded` when enabling summaryCalculations and minSpareRows](https://github.com/handsontable/handsontable/issues/5863)
- [x] 7.**FIXED**  [#5569 Numeric Type Does Not Work with Expected to Decimal ](https://github.com/handsontable/handsontable/issues/5569) 
  - [x] 8. [#5344 [0.35.1+] Numeric cell type percentage format not calculated ](https://github.com/handsontable/handsontable/issues/5344)
 - [x] 9. **FIXED**   [#5251 [3.0.0+] cell invalid after copy paste from excel in version PRO 4.0.0 ](https://github.com/handsontable/handsontable/issues/5251)
  - [x] 10. [#4884 Searching uses values hidden by numericFormat ](https://github.com/handsontable/handsontable/issues/4884)
  - [x] 11. [#4396 Numbers parsed incorrectly if "." is thousands separator, "," decimal separator and decimal part not specified](https://github.com/handsontable/handsontable/issues/4396)
  - [x] 12. [#4360 When changing cell type, cell editor does not dynamically change ](https://github.com/handsontable/handsontable/issues/4360)
- [x] 13.  **FIXED** [#4353 When the cell type is numeric, the formula does not work properly.](https://github.com/handsontable/handsontable/issues/4353)
  - [x] 14. [#4119 `Uncaught TypeError` in date cell type with numeric value.](https://github.com/handsontable/dev-handsontable/issues/425)
  - [x] 15. [#3402 Alter value before validation ](https://github.com/handsontable/handsontable/issues/3402)
  - [x] 16. [#2966 Cells function gets the property function in the col argument during validation ](https://github.com/handsontable/handsontable/issues/2966)
  - [x] 17. [#5848 Numeric cell type fails to validate -.n ](https://github.com/handsontable/handsontable/issues/5848)
----------
- [x] [#6308](https://github.com/handsontable/handsontable/issues/6308) Extended the Babel config with the possibility to use private methods, optional chaining and nullish coalescing operator.
- [x] [#6560 Remove travis CI config file](https://github.com/handsontable/handsontable/pull/6560)
- [x] [#6609 Add Hot logo to the repo with demo screenshot ](https://github.com/handsontable/handsontable/pull/6609) 
- [x] [#6612 Fix logo and screenshot path to proper develop branch](https://github.com/handsontable/handsontable/pull/6612) 
 - [x] [ handsontable/handsontable#6629 Bump dev-dependency "tree-kill"](https://github.com/handsontable/handsontable/pull/6629) 
- [x] [#6574  Separate testing and security audit in CI](https://github.com/handsontable/handsontable/issues/6574)
- [x] [#6565 Add CodeSandbox CI to our PR workflow handsontable/handsontable#6565](https://github.com/handsontable/handsontable/pull/6565)

**Comment by AMBudnik** [comment]
will do 👍

**Comment by aninde** [comment]
Testing Version size 4.02.2020

- Release/7.4.0 Dist size: 14 184 043 bytes (14,7 MB on disk) for 252 items
- Master Dist size: 14 034 684 bytes (14,5 MB on disk) for 244 items

Comparison with notes from the only PR will update of dependencies
Notes from testing handsontable/handsontable#10 on 14.01.2020 - only PR with dependencies bump handsontable/handsontable#6610
- Build from PR handsontable/handsontable#6610 size: 14 156 057 bytes (14,7 MB on disk) for 252 items
- Master Dist size: 13 977 728 bytes (14,5 MB on disk) for 252 items
