### ISSUE TITLE
Testing release 7.4.0 second stage

### ISSUE THREAD

**Issue by aninde** [handsontable/quality#24]
### Description
Supplement after first stage of testing 7.4.0 during code freeze https://github.com/handsontable/quality/issues/22 after @AMBudnik found [blocker](https://github.com/handsontable/handsontable/issues/6507#issuecomment-582392301) in [#6507](https://github.com/handsontable/handsontable/issues/6507) 

### Builds
https://cdn.jsdelivr.net/gh/handsontable/handsontable@667163c31860dd8545eb1b62c92042f6e0f8667d/dist/handsontable.full.js

 https://cdn.jsdelivr.net/gh/handsontable/handsontable@667163c31860dd8545eb1b62c92042f6e0f8667d/dist/handsontable.full.css 

### Testing checklist
- [x] build Handsontable
- [x] check size of dist and compare with result from first stage https://github.com/handsontable/quality/issues/22#issuecomment-581815016
- [x] execute e2e tests in various browsers
  - [x] Microsoft Edge
  - [x] Microsoft Dev Edge
  - [x] Chrome
  - [x] Firefox
  - [x] Safari
  - [x] Opera
  - [x] Brave (not officialy supported)
- [x] execute test for mobile devices
- [x] mobile - manual tests

### Test cases
- [x] Clicking the mouse on the Handsontable and next to it,
- [x] Click + hold on Handsontable and next to it
- [x] contextMenu
- [x] dropdownMenu
- [x] autofill
- [x] with enabled filters which is "Is equal" type, clicking with different buttons
- [x] repeat on Windows on Edgu and IE and for example Chromie
- [x] repeat on macOs on Chrome and Edge, Safari
- [x] repeat on Linux (Ubuntu) on FF
- [x] repeat what it possible on  iPad

### Related issues
Regression test of issue that was fixed by original 7.4.0
- [x] 7. [#5569 Numeric Type Does Not Work with Expected to Decimal ](https://github.com/handsontable/handsontable/issues/5569) 
The others were really fixed during previous releases. #5251 was fixed by 7.3.0. #4353. was fixed by 7.0.0.
- [x] does README.md was updated? [#6560 Remove travis CI config file](https://github.com/handsontable/handsontable/pull/6560)

### Requirements
[#6701 Fix inconsistency in how the context menu closes ](https://github.com/handsontable/handsontable/pull/6701#pullrequestreview-356654634)
