### ISSUE TITLE
[Handsontable] Testing release 7.4.1

### ISSUE THREAD

**Issue by aninde** [handsontable/quality#28]
### Description
First stage - testing 7.4.0 https://github.com/handsontable/quality/issues/22
Second stage - testing 7.4.0 https://github.com/handsontable/quality/issues/24

RN: https://github.com/handsontable/handsontable/releases/

### Builds
https://cdn.jsdelivr.net/gh/handsontable/handsontable@62db142fe201f9ade5c45cd3e921107b3d93f75b/dist/handsontable.full.css

https://cdn.jsdelivr.net/gh/handsontable/handsontable@62db142fe201f9ade5c45cd3e921107b3d93f75b/dist/handsontable.full.js

**Branch** 
https://github.com/handsontable/handsontable/tree/release/7.4.1

### Testing checklist
- [x] build Handsontable
- [x] build wrappers - React, Angular, Vue
- [x] check size of dist and compare with result from first stage https://github.com/handsontable/quality/issues/22#issuecomment-581815016
- [x] execute e2e tests in various browsers
  - [x] Microsoft Edge
  - [x] Microsoft Dev Edge
  - [x] Chrome
  - [x] Firefox
  - [x] Safari
  - [x] Opera
  - [x] Brave (not officialy supported)
- [x] mobile - manual tests 
   - [x] editor

### Test cases
- [x] Clicking the mouse on the Handsontable and next to it,
- [x] Click + hold on Handsontable and next to it
- [x] Click through contextMenu
- [x] Click through dropdownMenu
- [x] autofill vertical & horizontal
- [x] Click through cells with type Numeric
- [x] check formulas
- [x] check filters
- [x] check comments
- [x] check columnSummary
- [x] check filters which is "Is equal" type, clicking with different buttons
- [x] repeat on Windows on Edge and for example Chrome
- [x] repeat on macOs on Chrome and Edge, Safari
- [x] mobile: editor, every possible feature
- [x] repeat what it possible on  iPad

### Related issues
Regression test of issue that was fixed by original 7.4.0
- [x] [#6710 Error at resize of window after update to Chrome 80](https://github.com/handsontable/handsontable/issues/6710)
- [x] [#6707 [7.4.0] After Updating mobile editing does not work](https://github.com/handsontable/handsontable/issues/6707)
- [x] 7. [#5569 Numeric Type Does Not Work with Expected to Decimal ](https://github.com/handsontable/handsontable/issues/5569) 
The others were really fixed during previous releases. #5251 was fixed by 7.3.0. #4353. was fixed by 7.0.0.
- [x] does README.md was updated? [#6560 Remove travis CI config file](https://github.com/handsontable/handsontable/pull/6560)
- [x] [blocker for 7.4.0 found by @AMBudnik ](https://github.com/handsontable/handsontable/issues/6507#issuecomment-582392301) in [#6507](https://github.com/handsontable/handsontable/issues/6507) 
- [x] [#6459 white border on Windows](https://github.com/handsontable/handsontable/issues/6459)

### Pull requests
[#6711 Fixed `closest` helper](https://github.com/handsontable/handsontable/pull/6711)
[#6709 Fix dbl click events on mobile devices (touch events)](https://github.com/handsontable/handsontable/pull/6709)
[#6624 Remove background-clip CSS prop](https://github.com/handsontable/handsontable/pull/6624)
