### ISSUE TITLE
[HyperFormula] Testing

### ISSUE THREAD

**Issue by aninde** [handsontable/quality#3]
### Description

Testing the new product - HyperFormula. 
Epic. Work was done within smaller issues.

[Project repository](https://github.com/handsontable/hyperformula)

### To Do
- [x] Gathering requirements
- [x] Requirements analysis
- [x] Rethinking the testing stages
- [x] Establishing tests
- [ ] Planning chores
- [ ] Test implementation & development

### Releted issues
**Stage 1:**
#1 [HyperFormula] Acceptance testing of build-in formulas  
#2 [HyperFormula] Kitchensink testing 
#14 Conformance: engine & comparison operators based on small evaluator gruop
https://github.com/handsontable/quality/issues/19 Support for IE 10 and 11

**Stage 2 before release**
https://github.com/handsontable/quality/issues/27 Smoke testing  based on spreadsheet files
https://github.com/handsontable/quality/issues/29 Acceptance testing based on spreadsheet files
### 1. Syntax - based on ODFF
- [ ] Small evaluator group - [basic limit](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__711846_826425813) https://github.com/handsontable/hyperformula/issues/61, [tests](https://github.com/handsontable/hyperformula/blob/conformance/test/conformance/small-group-evaluator.spec.ts)
- [ ] arithmetic operations - more details in [quality/#33](https://github.com/handsontable/quality/issues/33)
- [x] comparision operations - some tests were already written: [booleans](https://github.com/handsontable/hyperformula/blob/conformance/test/parser/boolean-operators.spec.ts), [operators](https://github.com/handsontable/hyperformula/blob/conformance/test/conformance/operators.spec.ts), we can add more edge cases
- [x] text operations
- [x] whitespace - https://github.com/handsontable/hyperformula/issues/68 some tests were already [written](https://github.com/handsontable/hyperformula/blob/conformance/test/parser/white-spaces.spec.ts), we can add more edge cases 
- [x] errors, errors propagation-  some tests were already [written](https://github.com/handsontable/hyperformula/blob/conformance/test/parser/error-literals.spec.ts), we can add more edge cases 
- [x] type coercion [to scalar](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1017982_715980110), [to number](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1017988_715980110), [to Logical](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1018002_715980110), [to txt](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1018004_715980110), some tests were already [written](https://github.com/handsontable/hyperformula/blob/conformance/test/interpreter/coercions.spec.ts)
- [x] separators https://github.com/handsontable/hyperformula/issues/15, some tests were already [written](https://github.com/handsontable/hyperformula/blob/conformance/test/format/format-interpreter.spec.ts), but we can add more edge cases
- [ ] optional params in functions - after https://github.com/handsontable/hyperformula/issues/76
- [ ] cell references https://github.com/handsontable/hyperformula/issues/198
- [ ] sheet references https://github.com/handsontable/hyperformula/issues/198
- [ ] range references
- [x] date - some tests were already written [date](https://github.com/handsontable/hyperformula/blob/conformance/test/date.spec.ts), [leap year and max and min date](https://github.com/handsontable/hyperformula/blob/conformance/test/conformance/function-date.spec.ts), [date arithmetic](https://github.com/handsontable/hyperformula/blob/conformance/test/interpreter/date-arithmetic.spec.ts)
- [ ] time - after https://github.com/handsontable/hyperformula/issues/229
- [ ] duration - after https://github.com/handsontable/hyperformula/issues/229 
- [x] empty Values - [ready tests](https://github.com/handsontable/hyperformula/blob/conformance/test/interpreter/nullvalue.spec.ts)
- [ ] boolean - some were done as [comparison operators tests](https://github.com/handsontable/quality/issues/14) and [zero, null, empty](https://github.com/handsontable/hyperformula/blob/conformance/test/conformance/zero-null-EmptyValue.spec.ts), we can add more edge cases
- [ ] number, 
- [x] [infinity](https://github.com/handsontable/hyperformula/blob/conformance/test/conformance/infinity.spec.ts), 
- [x] negative zero
- [x] string - some were done as [comparison operators tests](https://github.com/handsontable/quality/issues/14), we can add more edge cases
- [x] case sensitive https://github.com/handsontable/hyperformula/issues/66 ready [tests](https://github.com/handsontable/hyperformula/blob/conformance/test/interpreter/string-cmp.spec.ts)
- [x] percantage - some were done as [comparison operators tests](https://github.com/handsontable/quality/issues/14), we can add more edge cases
- [x] precision - ready [tests](https://github.com/handsontable/hyperformula/blob/conformance/test/interpreter/precision.spec.ts)
- [ ] Check changelog. All features and formulas should be up to date.

### 2. API https://github.com/handsontable/hyperformula/issues/7
- [ ] CRUD https://github.com/handsontable/hyperformula/issues/26 https://github.com/handsontable/hyperformula/issues/28 https://github.com/handsontable/hyperformula/issues/31 https://github.com/handsontable/hyperformula/issues/33 https://github.com/handsontable/hyperformula/issues/29 https://github.com/handsontable/hyperformula/issues/29 some test are already [written](https://github.com/handsontable/hyperformula/tree/conformance/test/cruds), we can add more edge cases 
- [ ] events https://github.com/handsontable/hyperformula/issues/135 WIP
- [ ] named expresion https://github.com/handsontable/hyperformula/issues/126 some test were already [written](https://github.com/handsontable/hyperformula/blob/conformance/test/named-expressions.spec.ts), we can add more edge cases
- [ ] copy, cut, paste
- [ ] batch https://github.com/handsontable/hyperformula/issues/32 https://github.com/handsontable/hyperformula/issues/18 - WIP, some tests were already [written](https://github.com/handsontable/hyperformula/blob/conformance/test/cruds/batch-operations.spec.ts), we coud add more edge cases 
- [ ] helpers https://github.com/handsontable/hyperformula/issues/32 https://github.com/handsontable/hyperformula/issues/30 https://github.com/handsontable/hyperformula/issues/24 - Formula helpers WIP
- [ ] language support https://github.com/handsontable/hyperformula/issues/22
- [ ] custom function supported
- [ ] config

### 3. Environment
- [ ] Operation system: Windows, IE 9? IE 10, IE 11, Edge, Chrome, Firefox https://github.com/handsontable/hyperformula/issues/1
- [ ] Operation system: macOS
- [ ] Browsers: Firefox, Chrome, Safari, Edge, Opera?
- [ ] Minified build
- [ ] Node
- [ ] Mobile: Android, iOs
- [ ] Mobile: Ipad, iOs 13?
- [ ] UMD, ES, CommonJS (TypeScript, WebPAck, Babel)

#### 3a. Performance 
- [ ] Performance testing (required by the spec?)
- [ ] Compare performance with 7.2.2 formula-plugin

#### 4. Functions - test cases will be based on ODFF 
- [ ] * wildcards -> *? regx? after https://github.com/handsontable/hyperformula/issues/220 https://github.com/handsontable/quality/issues/31
- [x] ready [interpreter tests](https://github.com/handsontable/hyperformula/tree/conformance/test/interpreter)
- [ ] functions from https://github.com/handsontable/hyperformula/issues/221
- [ ] Does all parameters are supported
- [ ] Does it work without optional parameters
- [ ] Can parameters be a reference to another cell
- [ ] Are the correct errors returned when something went wrong
- [ ] How does it behave when parameters are out of bounds (eg. -1 when it should be >0)
- [ ] It is possible to implement remaining functions
  

#### 5. Buisness examples 
- [ ] [Acceptance tests based on real spreadsheet data](https://github.com/handsontable/quality/issues/29)
- [ ] [Smoke test based on real spreadsheet data](https://github.com/handsontable/quality/issues/27)

**Stage before release plugin for Handsontable**
https://github.com/handsontable/quality/issues/2 KitchenSink test
