### ISSUE TITLE
[HyperFormula] Verification and validation of closed issues

### ISSUE THREAD

**Issue by aninde** [handsontable/quality#30]
### Description
We should check if the reported bugs are actually repaired, whether the tests pass.
Have the arrangements changed and should the tests be changed?

### List of closed issues
- [x] [Errors handling with some operators gives wrong result #145](https://github.com/handsontable/hyperformula/issues/145 )
- [x] [Error N/A with some operators gives wrong result #144](https://github.com/handsontable/hyperformula/issues/144)
- [x] [Improper VALUE! error on mathematical operations with booleans #173](https://github.com/handsontable/hyperformula/issues/173)
- [x] [Booleans and BLANK/EMPTY with operators gives wrog results #142](https://github.com/handsontable/hyperformula/issues/142)
- [x] [BLANK/EMPTY with operators gives wrog results #127](https://github.com/handsontable/hyperformula/issues/127)
- [x] [Absence of support for leap year and 28 February #139](https://github.com/handsontable/hyperformula/issues/139)
