### ISSUE TITLE
[HyperFormula] Testing API - stage 1

### ISSUE THREAD

**Issue by aninde** [handsontable/quality#35]
### Description
We need to check conformance with requirements of API

Due to the limited time, the tests will consist of verification of ready tests, or adding test cases.

More complicated tests e2e will be written in the next stage after developing test scenarios based on ready-made Excel sheets.

### Test cases:
- [x] CRUD https://github.com/handsontable/hyperformula/issues/26 https://github.com/handsontable/hyperformula/issues/28 https://github.com/handsontable/hyperformula/issues/31 https://github.com/handsontable/hyperformula/issues/33 https://github.com/handsontable/hyperformula/issues/29 https://github.com/handsontable/hyperformula/issues/29 some test are already [written](https://github.com/handsontable/hyperformula/tree/conformance/test/cruds), we can add more edge cases 
- [ ] events https://github.com/handsontable/hyperformula/issues/135 WIP
- [x] named expresion https://github.com/handsontable/hyperformula/issues/126 some test were already [written](https://github.com/handsontable/hyperformula/blob/conformance/test/named-expressions.spec.ts), we can add more edge cases
- [ ] copy, cut, paste
- [x] batch https://github.com/handsontable/hyperformula/issues/32 https://github.com/handsontable/hyperformula/issues/18 - WIP, some tests were already [written](https://github.com/handsontable/hyperformula/blob/conformance/test/cruds/batch-operations.spec.ts), we coud add more edge cases 
- [x] helpers https://github.com/handsontable/hyperformula/issues/32 https://github.com/handsontable/hyperformula/issues/30 https://github.com/handsontable/hyperformula/issues/24 - Formula helpers WIP
   - [x] Is this sheet name optional?
  - [x] What would happen if everything is absolute?
  - [x] What about mixed adressing?
  - [x] Whether which formula depends on the specific Cell or sheets
  - [x] Each function via calculate formula
  - [x] Check with SUM
  - [x] Add up if the given value is greater than A1 - SUMIF
  - [x]  What if there are new references?
- [ ] language support https://github.com/handsontable/hyperformula/issues/22
- [ ] custom function supported
- [ ]  addColumns
- [x]     addNamedExpression
- [ ]     addRows
- [x]     addSheet
- [x]     batch
- [x]     calculateFormula
- [x]     changeNamedExpression
- [ ]     clearClipboard
- [x]     clearSheet
- [ ]     copy
- [ ]     countSheets
- [ ]     cut
- [ ]     destroy
- [ ]     disableNumericMatrices
- [ ]     doesCellHaveFormula
- [ ]     doesCellHaveSimpleValue
- [ ]     doesSheetExist
- [ ]     forceApplyPostponedTransformations
- [ ]     getAllSheetsDimensions
- [ ]     getAllSheetsFormulas
- [ ]     getAllSheetsSerialized
- [ ]     getAllSheetsValues
- [ ]     getCellFormula
- [ ]     getCellSerialized
- [ ]     getCellType
- [ ]     getCellValue
- [ ]     getCellValueType
- [ ]     getNamedExpressionValue
- [ ]     getRangeFormulas
- [ ]     getRangeSerialized
- [ ]     getRangeValues
- [ ]     getSheetDimensions
- [ ]     getSheetFormulas
- [ ]     getSheetId
- [ ]     getSheetName
- [ ]     getSheetSerialized
- [ ]     getSheetValues
- [ ]     getStats
- [ ]     isCellEmpty
- [ ]     isCellPartOfMatrix
- [ ]     isItPossibleToAddColumns
- [ ]     isItPossibleToAddRows
- [ ]     isItPossibleToAddSheet
- [ ]     isItPossibleToClearSheet
- [ ]     isItPossibleToMoveCells
- [ ]     isItPossibleToMoveColumns
- [ ]     isItPossibleToMoveRows
- [ ]     isItPossibleToRemoveColumns
- [ ]     isItPossibleToRemoveRows
- [ ]     isItPossibleToRemoveSheet
- [ ]     isItPossibleToReplaceSheetContent
- [ ]     isItPossibleToSetCellContents
- [ ]     isThereSomethingToUndo
- [ ]     listNamedExpressions
- [ ]     moveCells
- [ ]     moveColumns
- [ ]     moveRows
- [x]     normalizeFormula
- [ ]     onNamedExpressionAdded
- [ ]     onNamedExpressionRemoved
- [ ]     onSheetAdded
- [ ]     onSheetRemoved
- [ ]     onSheetRenamed
- [ ]     onValuesUpdated
- [ ]     paste
- [ ]     removeColumns
- [ ]     removeNamedExpression
- [ ]     removeRows
- [ ]     removeSheet
- [ ]     renameSheet
- [ ]     setCellContents
- [ ]     setSheetContent
- [ ]     simpleCellAddressFromString
- [ ]     simpleCellAddressToString
- [ ]     undo
- [x]     validateFormula
- [ ]     buildEmpty
- [x]     buildFromArray
- [x]     buildFromSheets

### Requirements
Compatibility with http://127.0.0.1:5005/classes/_index_.hyperformulans.html 

### Documentation
Internal HyperFormula documentation generated on develop branch

Flow to create docs with Makefile. 
Should be changed after removing Makefile.
```
$ npm i
$ make setup
$ make doc
$ make servedoc
```
