### ISSUE TITLE
[8.0.0-beta2] Stage 3a  Retestings issues

### ISSUE THREAD

**Issue by aninde** [handsontable/quality#49]
### Description
Retesting issues that should be fixed.

### Chores
- [ ] Is the reported bug corrected now?
- [ ] Sensible bug hunting around the reported bug
- [ ] if there will be compare it to `Handsontable v7.4.0`, maybe it is not a regression of `8.0.0-beta2`
- [ ] Check is there a regression on Chrome, Firefox, Safari, Edge, IE?

Report new bugs found to the main Handsontable repository with the number of revision in tittle e.g. `[8.0.0-beta2-rev.1] Title`

### Test cases:

- [x] 1. - Fixed an issue where Hidden columns become visible when the user ran `updateSettings` [#4121](https://github.com/handsontable/handsontable/issues/4121)
- [x] 2. - Fixed an issue where using `hiddenColumns` and `stretchH` showed a redundant horizontal scrollbar [#4181](https://github.com/handsontable/handsontable/issues/4181)
- [x] 3. - Fixed an issue in which ff the last column was a hidden column and stretchH was enabled, the last column was displayed [#4370](https://github.com/handsontable/handsontable/issues/4370)
- [x] 4. - Fixed an issue where `updateSettings` performance was very low because of `hiddenColumns` being rendered [#4381](https://github.com/handsontable/handsontable/issues/4381)
- [ ] 5. - Fixed the broken height header when both column height and hidden column were used [#4631](https://github.com/handsontable/handsontable/issues/4631)
- [ ] 6. - Fixed an issue where collapse was not working correctly with custom cell rendrers [#4716](https://github.com/handsontable/handsontable/issues/4716)
- [ ] 7. - Fixed an incorrect header name when user defined morec olumns in the `nestedHeaders` plugin [#4716](https://github.com/handsontable/handsontable/issues/4716)
- [ ] 8. - Fixed an issue where `hiddenColumns` did not work properly with `columnSorting` [#5571](https://github.com/handsontable/handsontable/issues/5571)
- [x] 9. - TO BE CHECKED- Fixed an issue where `manualColumnMove` should work with `hiddenColumns` [#5598](https://github.com/handsontable/handsontable/issues/5598)
- [x] 10. - Fixed an issue where `hiddenColumns` option interfered with the keyboard movement [#5704](https://github.com/handsontable/handsontable/issues/5704)
- [ ] 11. - Fixed an issue where after hiding the first two rows, the row headers became de-synchronized by 1px. [#5817](https://github.com/handsontable/handsontable/issues/5817)
- [x] 12. - Fixed an issue where hiding columns affected selection of hidden columns [#5871](https://github.com/handsontable/handsontable/issues/5871)
- [x] 13. - Fixed an issue where if `collapsibleColumns` were set to `true` it was impossible to cannot exit selection mode [#5875](https://github.com/handsontable/handsontable/issues/5875)
- [ ] 14. - Fixed an issue where `hiddenColumns` did not work properly with `autoWrapRow/autoWrapCol` [#5877](https://github.com/handsontable/handsontable/issues/5877)
- [x] 15. - Fixed an issue on IE where hiding the first column caused a display of double border for top left corner [#5881](https://github.com/handsontable/handsontable/issues/5881)
- [x] 16. - Fixed an issue where `nestedHeaders` duplicated a header name if more columns are added [#5882](https://github.com/handsontable/handsontable/issues/5882)
- [x] 17. - Fixed an issue where `hiddenColumns` plugin unset cell's `renderer` [#5883](https://github.com/handsontable/handsontable/issues/5883)
- [x] 18. - Fixed an issue where `hiddenColumns` had stored visual indexes and should have used physical indexes [#5909](https://github.com/handsontable/handsontable/issues/5909)
- [ ] 19. - Fixed an issue where additional row was added during copy/paste operations and with hidden rows/columns enabled [#5961](https://github.com/handsontable/handsontable/issues/5961)
- [x] 20. - Fixed an issue where hidden columns should be unrecoverable [#6113](https://github.com/handsontable/handsontable/issues/6113)
- [x] 21. - Fixed an issue where row selection ignored columns that are hidden at the end [#6181](https://github.com/handsontable/handsontable/issues/6181)
- [x] 22. - Fixed an issue where defining data with more data than used in `columns` caused an issue with showing column once it was hidden [#6426](https://github.com/handsontable/handsontable/issues/6426)
- [ ] 23. - Fixed an issue where hiding rows while there was a merged area involved caused data shifting and unexpected merged area coordinates [#6376](https://github.com/handsontable/handsontable/issues/6376)
- [ ] 24. - Fixed an issue where some headers were gone when hidden and shown again [#6395](https://github.com/handsontable/handsontable/issues/6395)
- [x] 25. - Fixed an issue where `colHeader` was truncated after moving `hiddenColumn` [#6463](https://github.com/handsontable/handsontable/issues/6463)
- [x] 26. - Fixed an issue where the last hidden column was visible upon column resizing [#6557](https://github.com/handsontable/handsontable/issues/6557)
- [x] 27. - Fixed an issue where with hiding columns after moved them manually [#6668](https://github.com/handsontable/handsontable/issues/6668)
- [ ] 28. - Fixed an issue where copy-and-paste worked wrong in a cell that was then hidden and uncovered again [#6742](https://github.com/handsontable/handsontable/issues/6742)
- [ ] 29. - Fixed an issue where too many values were pasted when the column was hidden [#6743](https://github.com/handsontable/handsontable/issues/6743)
- [x] 30. - Fixed an issue where expanding a collapsed column caused expanding of a child columns except for the the first one [#5792](https://github.com/handsontable/handsontable/issues/5792)
- [x] 31. - Fixed an issue where setting `columnSorting` to `true` (on initialization or via `updateSettings`) made headers non-collapsible programmatically via `collapseAll` method [#4999](https://github.com/handsontable/handsontable/issues/4999)

Not placed in Release notes (7.05 FYI @scarletfog )
Related to [PR 6716](https://github.com/handsontable/handsontable/pull/6716 )
- [x] 32. currentColClassName doesn't work properly with nestedHeaders [#5861](https://github.com/handsontable/handsontable/issues/5861)
- [x] 33. Selection skips the highest parent [#6770](https://github.com/handsontable/handsontable/issues/6770)

### Documentation
- Refactored hidden indexes [#6595](https://github.com/handsontable/handsontable/issues/6595)
- Feature/index mapper nested headers fix [#6716] (https://github.com/handsontable/handsontable/pull/6716)
- [8.0.0] Hidden Indexes refactor https://github.com/handsontable/handsontable/pull/6716
