### ISSUE TITLE
SVG Borders - stage 1 and stage 2

### ISSUE THREAD

**Issue by aninde** [handsontable/quality#5]
### First stage
- [x] Testing PR https://github.com/handsontable/handsontable/pull/6157
- [x] Testing checklist https://github.com/handsontable/handsontable/issues/6467

### Second stage - retest and regression tests
Testing [bugs](https://github.com/handsontable/handsontable/issues/6467#issuecomment-561557696) found in the first stage
Two PRs: 
 - [x] https://github.com/handsontable/handsontable/pull/6593 (SVG borders: Respond to dynamic changes in selection border color and width)

    Builds: 
    `.css`
    https://gist.githack.com/aninde/0616665053abd68b24df768c9d061084/raw/01f332ad7a3df7575d248577310419fe35536b6a/handsontable.full.min.css
    `.js`
    https://gist.githack.com/aninde/d78aa1e84304254cda4629f7b5673d40/raw/3668a12334e82f4dd18e9cb4a0ca1d0a42980c64/handsontable.full.min.js

 - [x]  https://github.com/handsontable/handsontable/pull/6594 (SVG borders: refactor Overlay classes, fix fast scrolling)

    Builds: 
    `.css`
https://gist.githack.com/aninde/ee118a4a6edf7e10baa31b2a9fdff0a3/raw/7d3a1b7fe55021ade6a3ed82eeacb8183696fd9e/handsontable.full.min.css
    `.js`
https://gist.githack.com/aninde/263e58cf59ef82153cb28b3f51c866f0/raw/9fc1643fb42ea23d1629c747bbe2ccfa65a082a7/handsontable.full.min.js

### Found bugs
- [ ] 1. [ #6627 [8.0.0-svg-PR#6593] colors order on fixed borders ](https://github.com/handsontable/handsontable/issues/6627)
- [ ] 2. [ #6628 [8.0.0-svg] selection, fill and autoFill covers fixedBorder or frozen-border ](https://github.com/handsontable/handsontable/issues/6628)
- [ ] 3. [#6626 Cell selection on print](https://github.com/handsontable/handsontable/issues/6626) 
- [ ] 4. [#6639 [8.0.0-svg] Introduce "Frozen line" to mark the edge of fixed rows/columns ](https://github.com/handsontable/handsontable/issues/6639)

#### Discussion
- [ ] https://github.com/handsontable/handsontable/pull/6594#issuecomment-573666601 - or maybe bug?

### Third stage  
was moved to separate issue https://github.com/handsontable/quality/issues/8

### How it was tested?

Locally and with demos
https://jsfiddle.net/aninde/4zkrvqgs/ - stage 1 v. 
WIP
