### ISSUE TITLE
[8.0.0-beta] Verification of releted issues

### ISSUE THREAD

**Issue by aninde** [handsontable/quality#52]
### Description

1. **Released with 8.0.0-beta1**
Needs re-tests with `8.0.0-beta2` and closing on GH.

- [x] 1. https://github.com/handsontable/handsontable/issues/6755 
- [x] 2. https://github.com/handsontable/handsontable/issues/6703 
- [x] 3. https://github.com/handsontable/handsontable/issues/6700
- [x] 4. https://github.com/handsontable/handsontable/issues/6464
- [x] 5. https://github.com/handsontable/handsontable/issues/6428 
- [x] 6. https://github.com/handsontable/handsontable/issues/6410 
- [x] 7. https://github.com/handsontable/handsontable/issues/6412 
- [x] 8. https://github.com/handsontable/handsontable/issues/6320 
- [x] 9. https://github.com/handsontable/handsontable/issues/6218
- [x] 10. https://github.com/handsontable/handsontable/issues/5328
- [x] 11. https://github.com/handsontable/handsontable/issues/6703
- [x] 12. https://github.com/handsontable/handsontable/issues/6845
- [x] 13. https://github.com/handsontable/handsontable/issues/6371
- [x] 14. https://github.com/handsontable/handsontable/issues/6347
- [x] 15. https://github.com/handsontable/handsontable/issues/6346
- [x] 16. https://github.com/handsontable/handsontable/issues/6232
- [x] 17. https://github.com/handsontable/handsontable/issues/6295
- [x] 18. https://github.com/handsontable/handsontable/issues/6167
- [x] 19. https://github.com/handsontable/handsontable/issues/6477
- [x] 20. https://github.com/handsontable/handsontable/issues/6489
- [x] 21. https://github.com/handsontable/handsontable/issues/6506
- [ ] 22.~https://github.com/handsontable/handsontable/issues/6508~ not releted to `v8`
- [x] 23. https://github.com/handsontable/handsontable/issues/6497
- [x] 24. https://github.com/handsontable/handsontable/issues/6539
- [x] #6334 Inconsistent selection using the right mouse button for first row/column
- [x] #7061 Problems with adding rows from the corner when all rows are trimmed
- [x] #6327 Inconsistency with context menu 'Remove columns' option
- [x] #7005 We cannot set focus to a column to open context menu after applying a filter
- [x] #5906 Selection of a whole row does not happen consequently after selecting a row header.

2. **After beta.2 there are more issues that are connected to the changes we've made:**

- [x] #3328  beforeColumnResize and beforeRowResize first argument is column width 
- [x] #5208 Filtering results in blank rows 
- [x] #1501 Sorting passing logical index through afterChange event 
- [x] #5125 AutoFill not works will there is a mergedCell in the target area 
- [x] #5999 handsontable 7.0.2 context menu issue with multiple selected rows in case of 1st column hidden 
- [ ] #6051 Wrong cell meta removed when deleting rows 
- [x] #6381`walkontable.css` and `handsontable.css` stylesheets are not in sync 
- [x] #6397 Sorting indicator moves incorrectly when adding a column 
- [x] #6413 colHeaders order is not updated after manual move with empty object data source 
- [x] #6669 Undoing removing hidden rows makes rows exposed 
- [x] #6743 Too many values pasted when column is hidden 
- [x] #6742 Paste off-by-one after show/hide column 
- [x] #6728 Copy doesn't work when selected hidden column 
- [x] #6703 [8.0.0] The cell meta is being retrieved using the wrong coordinates 
- [x] #6833 skipColumnOnPaste and skipRowOnPaste when added to table settings hang the browser down after pasting 
- [x] #6794 When nestedHeaders are enabled wrong column is removed 
- [x] #6934 Trimming rows causes the newly added rows by paste to remain 
- [x] #6965 After moving row from bottom to top the row indexes changes if the first row is hiding.  
- [x] #6787 nestedHeaders blocks rendering of rows if the first row exceeds the viewport 
- [x] #6518 [8.0.0] Moving data isn't working properly, when there are skipped indexes 
- [x] #6004 ManualColumnMove dragging breaks after updateSettings() 
- [x] #6001 Freezing columns do not work with nestedHeaders 
- [x] #5525 afterRemoveRow, afterInserRow, afterRemoveCol, afterInsertCol are called before cellMeta is updated 
- [x] #5543 Error after update settings rendering twice and picking wrong renderer functions 
- [x] #5792 BUG: Expand collapsed column, is expanding also 'child' collapsed columns, except the first child 

---
- [x] #6309 Set data at *physical* row instead of visual. **setSourceDataAtCell was added**
