### ISSUE TITLE
Testing checklist for devs PR#6610

### ISSUE THREAD

**Issue by aninde** [handsontable/quality#6]
### Description
I was asked to create a testing checklist of PR https://github.com/handsontable/handsontable/pull/6610 to help developers test it. 

### Chores

- [x] getting to know the changes
- [x] getting to know the requirements
- [x] design test for PR and related issues
- [x] collecting ideas and creating a checklist
