### ISSUE TITLE
8.0.0 release 

### ISSUE THREAD

**Issue by aninde** [handsontable/quality#7]
#### Description
Issue gathering tasks related to maintaining the highest quality of the upcoming version 8.0.0-beta2

#### Branch 
https://cdn.jsdelivr.net/gh/handsontable/handsontable@pre-8.0.0-beta.2/dist

#### Test plan
**1 stage: Acceptance tests - smoke tests** 
checking if the version is building correctly, whether it can be tested further
**1a** https://github.com/handsontable/quality/issues/45
- [x] build with every wrapper
- [x] React
- [x] Angular
- [x] Vue
- [x] Check their size

**1b** https://github.com/handsontable/quality/issues/50
- [x] Build and run documentation 
- [x] Correct version of documentation is builded
- [x] Updated demos - click through all the demos, checking all plugins separately

**1c** done by developers during code review
**Performance lab**
- [x] fast tests, differences on diagrams, comparing to older versions

**Stage 2: Acceptance tests - sanity tests** https://github.com/handsontable/quality/issues/46
- [x] checking if new feature and breaking change work as described

**Stage 3a  Retesting fixed issues**  https://github.com/handsontable/quality/issues/49
- [x] Retesting all issues that should be fixed.
- [x] Is the reported bug corrected now?
- [x] Sensible bug hunting around the reported bug.
- [x] Check is there a regression on all supported browsers.

**Stage 3b  Regression testing - bug hunting**
- [x] - on every wrapper https://github.com/handsontable/quality/issues/55
- [x] Usability & appearance https://github.com/handsontable/quality/issues/47
- [x] Responsiveness https://github.com/handsontable/quality/issues/48
- [x] Accessibility 
    - [x] contrast
- [x] Main feauters
- [x] Mobile
   - [x] editor
   - [x] Responsiveness
- [x] Mouse events, LMB i RMB
- [x] Keyboards shortcuts

**Stage 4 Regression testing - Environment testing**
- [x] Running ready test on all supported browsers

**Stage 5 Performance lab**
- [x] check performance of last-ready for release version for blogpost

### Releted
- Refactored hidden indexes [#6595](https://github.com/handsontable/handsontable/issues/6595)
- Feature/index mapper nested headers fix [#6716] (https://github.com/handsontable/handsontable/pull/6716)
- [8.0.0] Hidden Indexes refactor https://github.com/handsontable/handsontable/pull/6716
