### ISSUE TITLE
[9.0.0] Tesing Handsontable with HyperFormula

### ISSUE THREAD

**Issue by aninde** [handsontable/quality#95]
### Description
Testing checklist

### Reference
<link to the release branch>
<link to changelog>

### Chores
**Integration test**
- [x] add HyperFormula as an engine of formulas and test it with every Handsontable feature
   - [x] mainly those that use visual indexes (@aninde, @AMBudnik, @wszymanski) done
   - [x] test every docs demo with HF as engine
    - [x] React (@Osky772 )
    - [x] Vue (@Siemienik )
    - [x] Angular (blocked for now)
- [ ] build with each wrapper
  - [x] React
  - [x] Vue
  - [x] Angular (blocked for now)

### Smoke tests
HF engine test 
 - [x] smoke tests with ready data sets
    - [x] Vanilla
    - [x] React
    - [x] Angular
    - [x] Vue

### Retests
- [x] https://github.com/handsontable/handsontable/issues/4357 - change, blocked by HF
- [x] https://github.com/handsontable/handsontable/issues/4430 - works well
- [x] https://github.com/handsontable/handsontable/issues/4654 - works well
- [x] https://github.com/handsontable/handsontable/issues/4668 - bloked by regression
- [x] https://github.com/handsontable/handsontable/issues/4675 - works well
@AMBudnik 
- [x] https://github.com/handsontable/handsontable/issues/5870 - works well
- [x] https://github.com/handsontable/handsontable/issues/5872 - works well
- [x] https://github.com/handsontable/handsontable/issues/6248 - works well
- [x] https://github.com/handsontable/handsontable/issues/6932 - works well

### Documentation tests
   - [x] Header tooltips
   - [x] formulas
     - [x] formulas API
     - [x] formulas demo
   - [x] migration guide?
- [x] Handsontable API

### Breaking changes:
- [x] formula API
   - [ ] batch
- [x] hooks beforeAutofill: signature change
- [x] afterAutofill: signature change

### Code freeze:
- [x] performance
- [x] package size

### After release
- [x] retesting all issues form https://github.com/handsontable/handsontable/issues/6466 
- [ ] https://github.com/handsontable/handsontable/issues/4693

Environments:
Firefox, Chrome, Internet Explorer, Edge, Safari, Opera
macOS, Windows 10

**Comment by AMBudnik** [comment]
I've checked all the examples at https://dev.handsontable.com/docs/next/examples/#miscellaneous and they all work as expected (as in the previous version)

**Comment by aninde** [comment]
### Code freeze 25.05

### Official RN:
https://gist.github.com/jansiegel/80ba8aab608e4e73ef006b324cc3c211
suplement 
https://github.com/handsontable/handsontable/blob/develop/.changelogs/8095.json

### Issues found during the first testing iteration and not fixed yet:
**(Current, reported bugs)**

1. - [ ] [9.0.0] Cells' formulas miss calculation when the value is deleted [#8044](https://github.com/handsontable/handsontable/issues/8044) bloked by https://github.com/handsontable/handsontable/pull/8087#pullrequestreview-667655794
2. - [ ]  [9.0.0] Nested rows don't work well while HyperFormula is enabled as formulas engine [#8048](https://github.com/handsontable/handsontable/issues/8048)
3. - [ ] [9.0.0] column width is not updated when formula result needs more space (number of chars is greater than on the init) [#8061](https://github.com/handsontable/handsontable/issues/8061) ?
4. - [ ] [9.0.0] Validation is broken when cell data being changed. [#8066](https://github.com/handsontable/handsontable/issues/8066)
5. - [ ] [9.0.0] Enabling HF prevents default cell initialization [#8069](https://github.com/handsontable/handsontable/issues/8069)
6. - [ ] [9.0.0] When the new formula engine is defined undo does not bring back data in the previously removed columns [#8076](https://github.com/handsontable/handsontable/issues/8076)
7. - [ ] [9.0.0] When we cause the formula to throw a #REF! error with an action undoing it doesn't clear the error [#8078](https://github.com/handsontable/handsontable/issues/8078)


#### Issues found and fixed:
- [x] [9.0.0] Sorting doesn't work while HyperFormula is enabled as formulas engine [#8046](https://github.com/handsontable/handsontable/issues/8046)
- [x] only collapsing and uncollapsing nested Rows https://github.com/handsontable/handsontable/issues/8048#issuecomment-844322746
- [x] [9.0.0] Filters don't work while HyperFormula is enabled as new formulas engine [#8049](https://github.com/handsontable/handsontable/issues/8049) main case fixed, advanced operation with sorting can truncates col header
- [x] [9.0.0] Data population don't work properly while HyperFormula is enabled [#8050](https://github.com/handsontable/handsontable/issues/8050)
- [x] [9.0.0] Validation does not work for cells that contain formulas [#8053](https://github.com/handsontable/handsontable/issues/8053) - fixed, but it's not perfect
- [x] [9.0.0] Uncaught Error - Table breaks when minSpareRows or minSpareCols are added [#8054](https://github.com/handsontable/handsontable/issues/8054) - partially fixed
- [x] The table throws errors when the formulas sheet name contains a dash [#8057](https://github.com/handsontable/handsontable/issues/8057) -still broken
- [x] [9.0.0] Moving columns/rows doesn't work [#8058](https://github.com/handsontable/handsontable/issues/8058) - fixed
- [x] [9.0.0] ManualColumnFreeze freezes wrong columns when HF is used [#8060](https://github.com/handsontable/handsontable/issues/8060) - fixed
- [x] [9.0.0] Autofill truncates column header [#8063](https://github.com/handsontable/handsontable/issues/8063) -fixed


### Testing chores
- :point_up:  retesting fixed issues @aninde @AMBudnik 
- retesting & regression testing on wrappers - test cases prepared and split between @Siemienik and @Osky772 
- performance-lab benchmark @budnix 
- regression testing @aninde 
- afterAutofill
- beforeAutofill
- documentation testing @aninde 
- smoke tests @aninde 

As supplement:

- [ ]  retesting issues with official v9 @aninde @AMBudnik 
- [x]  https://github.com/handsontable/handsontable/issues/4430 - fixed
- [x] https://github.com/handsontable/handsontable/issues/4654 - fixed
- [x] https://github.com/handsontable/handsontable/issues/4675 - fixed
- [x] https://github.com/handsontable/handsontable/issues/5870 - fixed
- [x] https://github.com/handsontable/handsontable/issues/6248 - fixed
- [x] https://github.com/handsontable/handsontable/issues/6932 - fixed

**Comment by aninde** [comment]
### Results after second test iteration
####  Reported regressions: 

1. - [ ] [9.0.0] Validation on dropdown cell is broken in specific case when dataset is number passed as strings [#8115](https://github.com/handsontable/handsontable/issues/8115)
2. - [ ] Moving a column with a formula in a cell changes the formula to its value [#8114](https://github.com/handsontable/handsontable/issues/8114)
3. - [ ] [9.0.0] Dataset isn't restored after undoing column removal on these column [#8113](https://github.com/handsontable/handsontable/issues/8113)
4. - [ ] [9.0.0] Enabling formulas change working of autofill: no new rows are added[ #8112](https://github.com/handsontable/handsontable/issues/8112)
5. - [ ] [9.0.0] Spare rows and columns are not visible if formulas as enabled [#8110](https://github.com/handsontable/handsontable/issues/8110)
6. - [ ] [9.0.0] We are not able to alter the number of rows by pasting data [#8109](https://github.com/handsontable/handsontable/issues/8109)
7. - [x] ~Missing TS for new Formulas plugin~ [#8108](https://github.com/handsontable/handsontable/issues/8109)
8. - [ ] [9.0.0] We are not able to block autofill when formulas are defined [#8107](https://github.com/handsontable/handsontable/issues/8107)
9. - [ ] [9.0.0] One e2e fails on Safari and FF [#8106](https://github.com/handsontable/handsontable/issues/8107)
10. - [ ] The MIN formula does not support column range notation [#8104](https://github.com/handsontable/handsontable/issues/8104)

**Comment by aninde** [comment]
### Issues found during the first testing iteration and not fixed yet:
**(Current, reported bugs)**

1. - [ ] [9.0.0] Cells' formulas miss calculation when the value is deleted [#8044](https://github.com/handsontable/handsontable/issues/8044) bloked by https://github.com/handsontable/handsontable/pull/8087#pullrequestreview-667655794
2. - [ ]  [9.0.0] Nested rows don't work well while HyperFormula is enabled as formulas engine [#8048](https://github.com/handsontable/handsontable/issues/8048)
3. - [x] [9.0.0] column width is not updated when formula result needs more space (number of chars is greater than on the init) [#8061](https://github.com/handsontable/handsontable/issues/8061) ?
4. - [x] [9.0.0] Validation is broken when cell data being changed. [#8066](https://github.com/handsontable/handsontable/issues/8066)
5. - [x] [9.0.0] Enabling HF prevents default cell initialization [#8069](https://github.com/handsontable/handsontable/issues/8069)
6. - [ ] [9.0.0] When the new formula engine is defined undo does not bring back data in the previously removed columns [#8076](https://github.com/handsontable/handsontable/issues/8076)
7. - [ ] [9.0.0] When we cause the formula to throw a #REF! error with an action undoing it doesn't clear the error [#8078](https://github.com/handsontable/handsontable/issues/8078)
