### ISSUE TITLE
WebdriverIO - visual regression automation

### ISSUE THREAD

**Issue by aninde** [handsontable/quality#99]
### Description
Visual regression automation is a must because it will speed up the quality checking process.

Until now, unit tests and e2e tests are used in Handsontable. 
We lack tests that take into account the visual parts of the table and interactions with the user. 
This gap is to be filled in with a tool developed on the basis of a previously prepared Storybook foundation.
We already have connected Storybook with Cypress, but WebdriverIO is a better tool, due to its support for all browsers.

### To do

- [x] proof of concept: connecting WebdriverIO to the Storybook
  - [x] implement possibility to run in different environments
- [ ] migration to the Handsontable/Quality repository
- [ ] documentation update
- [ ] README update 
    - [ ] how this should work?
    - [ ] how write tests?
    - [ ] how connect to the BrowserStack?
